# Generated by Django 5.2 on 2025-06-27 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MQTTMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(max_length=255, verbose_name="主题")),
                ("payload", models.TextField(verbose_name="消息内容")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="接收时间"),
                ),
                (
                    "qos",
                    models.IntegerField(
                        default=0,
                        help_text="MQTT服务质量等级(0, 1, 2)",
                        verbose_name="服务质量",
                    ),
                ),
            ],
            options={
                "verbose_name": "MQTT消息",
                "verbose_name_plural": "MQTT消息",
                "ordering": ["-timestamp"],
            },
        ),
    ]
